version: "3.8"

services:


    nginx:
        image: nginx:alpine
        restart: unless-stopped
        volumes:
            -   ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            -   ./src:/usr/share/nginx/html
        ports:
            -   80:80
        networks:
            -   default
            -   web
        depends_on:
            -   backend
#            -   frontend


    backend:
        build:
            context: backend
            dockerfile: Dockerfile
        container_name: backend
        networks:
            web:
                aliases:
                    -   backend


#    frontend:
#        build:
#            context: ./frontend
#            dockerfile: Dockerfile
#        container_name: frontend
#        networks:
#            web:
#                aliases:
#                    -   frontend
#        stdin_open: true


networks:
    web: