version: "3.8"

services:
    nginx:
        depends_on:
            - react
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
