version: "3.8"

services:


    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx
#        ports:
#            -   80:80
#            -   5000:5000
        networks:
            -   default
            -   web
        depends_on:
            -   backend
            -   frontend


    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        volumes:
            -   ./backend:/home/Projects/SezonowyOgrod/backend
        networks:
            web:
                aliases:
                    -   backend
        environment:
            -   FLASK_APP=core.py
            -   FLASK_ENV=development
            -   FLASK_DEBUG=1


    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        volumes:
            -   ./frontend:/home/Projects/SezonowyOgrod/frontend
        networks:
            web:
                aliases:
                    -   frontend
        stdin_open: true


networks:
    web: