version: "3.8"

services:

    sezonowyogrod-frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: sezonowyogrod-frontend
        restart: unless-stopped
        ports:
            -   "80:8080"
        networks:
            -   nginx_network
            -   sezonowyogrod_network


    sezonowyogrod-backend:
        build:
            context: backend
            dockerfile: Dockerfile
        container_name: sezonowyogrod-backend
        restart: unless-stopped
        ports:
            -   "5001:5001"
        networks:
            - nginx_network
            - sezonowyogrod_network


networks:
    nginx_network:
        external: true
    sezonowyogrod_network:
