version: "3.8"

services:

    sezonowyogrod-backend:
        build:
            context: backend
            dockerfile: Dockerfile
        container_name: sezonowyogrod-backend
        restart: unless-stopped
        ports:
            -   "5001:5001"
        networks:
            - nginx_network
            - sezonowyogrod_network

networks:
    nginx_network:
        external: true
    sezonowyogrod_network:

#    frontend:
#        build:
#            context: ./frontend
#            dockerfile: Dockerfile
#        container_name: frontend
#        networks:
#            web:
#                aliases:
#                    -   frontend
#        stdin_open: true


#    nginx:
#        build:
#            context: ./frontend
#            dockerfile: Dockerfile
#        restart: unless-stopped
#        volumes:
#            -   ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#        ports:
#            -   80:80
#        networks:
#            -   default
#            -   web
#        depends_on:
#            -   backend
##            -   frontend
