version: "3.8"

services:

    sezonowyogrod-frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: sezonowyogrod-frontend
        restart: unless-stopped
        ports:
            - "3003:3003"
        networks:
            -   sezonowyogrod_network


    sezonowyogrod-backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: sezonowyogrod-backend
        restart: unless-stopped
        ports:
            -   "5003:5003"
        networks:
            - sezonowyogrod_network


networks:
    sezonowyogrod_network:
        external: true
