version: "3.8"

services:

#    sezonowyogrod-frontend:
#        build:
#            context: ./frontend
#            dockerfile: Dockerfile
#        container_name: sezonowyogrod-frontend
#        restart: unless-stopped
#        ports:
#            -   "3000:3000"
#        networks:
#            -   nginx_network
#            -   sezonowyogrod_network
#        volumes:
#            -   /usr/share/nginx/html

    portfolio-nginx:
        image: nginx:alpine
        container_name: portfolio-nginx
        restart: unless-stopped
        ports:
                -   "80:80"
                -   "443:443"
        networks:
            -   nginx_network
            -   portfolio_network
        volumes:
            -   ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    sezonowyogrod-backend:
        build:
            context: backend
            dockerfile: Dockerfile
        container_name: sezonowyogrod-backend
        restart: unless-stopped
        ports:
            -   "5001:5001"
        networks:
            - nginx_network
            - sezonowyogrod_network


networks:
    nginx_network:
        external: true
    sezonowyogrod_network:
