version: "3.8"

services:


    nginx:
        image: nginx:alpine
        restart: unless-stopped
        volumes:
            -   ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            -   80:80
        networks:
            -   default
            -   web
        depends_on:
            -   backend
            -   frontend


    backend:
        build:
            context: backend
            dockerfile: Dockerfile
        container_name: backend
        volumes:
            -   ./backend:/home/Projects/SezonowyOgrod/backend
        networks:
            web:
                aliases:
                    -   backend


    backend2:
        build:
            context: backend2
            dockerfile: Dockerfile
        container_name: backend2
        volumes:
            -   ./backend:/home/Projects/SezonowyOgrod/backend2
        networks:
            web:
                aliases:
                    -   backend2


    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        volumes:
            -   ./frontend:/home/Projects/SezonowyOgrod/frontend
        networks:
            web:
                aliases:
                    -   frontend
        stdin_open: true


networks:
    web: